# Generated by Django 2.2 on 2021-05-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBQAStored',
            fields=[
                ('Ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quest_text', models.TextField()),
                ('Answer_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quest_make_sense', models.CharField(blank=True, max_length=100)),
                ('Reaction_thoughts', models.CharField(blank=True, max_length=100)),
                ('Advice', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('Pred_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pred_type', models.CharField(blank=True, max_length=100)),
                ('Pred_name', models.CharField(blank=True, max_length=100)),
                ('Pred_input_str', models.CharField(blank=True, max_length=100)),
                ('Pred_number', models.IntegerField()),
                ('Pred_reaction', models.CharField(blank=True, default='NEUTRAL', max_length=10)),
                ('Person_name', models.CharField(blank=True, max_length=50)),
                ('Date_today', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='Profiles'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
